org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.java.home                 = /usr/lib/jvm/java-26-openjdk

# Common
java_version                         = 26
hytale_version                       = 0.+
manifestServerVersion                = >=0.5.0 <0.7.0

# Publishing
modtale_uuid                         = aa85084a-f659-4f95-8f9c-c2ebee5d77cf
modifold_id                          = xSH4yg
curseforgeID                         = 1657477

# Mod options
group                                = com.riprod.effectly
manifest_group                       = Riprod
mod_name                             = Effectly
main_class                           = com.riprod.effectly.EffectlyPlugin
mod_author                           = Riprod
mod_id                               = Effectly
mod_license                          = CC0-1.0
mod_description                      = Effectly - Library mod for player effects
mod_credits                          = Riprod, gchougland
mod_logo                             = icon-256.png
mod_url                              = https://modtale.net/mod/effectly
mod_issues                           = https://github.com/itsriprod/effectly/issues
mod_sources                          = https://github.com/itsriprod/effectly
version                              = 1.4.0
includes_pack                        = true
disabled_by_default                  = false
patchline                            = release
load_user_mods                       = false
manifest_dependencies                = 
manifest_opt_dependencies            = 